data: 
  train_dir_path: './CVC-ClinicDB/Original/'
  label_dir_path: './CVC-ClinicDB/Ground Truth/'
train:
  batch_size: 1
  shuffle: True 
  input_dim: [192, 256]
  num_channels: 3 
  epochs: 10 
  learning_rate: 0.001 
  betas: [0.9, 0.999]
  T_max: 30
  eta_min: 0.0001
  test_size: 0.3
  random_state: 43 
  save_model_path: null
logging: 
  filename: 'train_logs.log'
  level: INFO 
