data: 
  train_dir_path: './CVC-ClinicDB/Original/'
  label_dir_path: './CVC-ClinicDB/Ground Truth/'
train:
  batch_size: 4
  shuffle: True 
  input_dim: [256, 192]
  num_channels: 3 
  epochs: 100 
  learning_rate: 0.001 
  betas: [0.9, 0.999]
  T_max: 30
  eta_min: 0.0001
  test_size: 0.3
  random_state: 43 
  save_model_path: "DCUnet.pt"
  log_every_n_steps: 20
logging: 
  level: INFO 
